"""Repository interfaces for the identity domain.

These interfaces are defined in the domain layer so application services
depend on abstractions, not on SQLAlchemy or any storage implementation.
"""

from __future__ import annotations

from typing import Protocol

from openrag_lab.domain.identity.models import (
    Document,
    GlobalRole,
    Permission,
    Role,
    Tenant,
    TenantUserRole,
    User,
    UserGlobalRole,
)
from openrag_lab.domain.shared.ids import (
    DocumentId,
    GlobalRoleId,
    RoleId,
    TenantId,
    UserId,
)


class TenantRepository(Protocol):
    async def find_by_id(self, tenant_id: TenantId) -> Tenant | None: ...
    async def find_by_slug(self, slug: str) -> Tenant | None: ...
    async def save(self, tenant: Tenant) -> None: ...
    async def list_all(self) -> list[Tenant]: ...


class UserRepository(Protocol):
    async def find_by_id(self, user_id: UserId) -> User | None: ...
    async def find_by_username(self, username: str) -> User | None: ...
    async def save(self, user: User) -> None: ...
    async def list_by_tenant(self, tenant_id: TenantId) -> list[User]: ...


class RoleRepository(Protocol):
    async def find_by_id(self, role_id: RoleId) -> Role | None: ...
    async def find_by_name(self, name: str) -> Role | None: ...
    async def list_all(self) -> list[Role]: ...
    async def save(self, role: Role) -> None: ...


class GlobalRoleRepository(Protocol):
    async def find_by_id(self, role_id: GlobalRoleId) -> GlobalRole | None: ...
    async def find_by_name(self, name: str) -> GlobalRole | None: ...
    async def list_all(self) -> list[GlobalRole]: ...
    async def save(self, role: GlobalRole) -> None: ...


class PermissionRepository(Protocol):
    async def list_all(self) -> list[Permission]: ...
    async def list_by_names(self, names: set[str]) -> list[Permission]: ...


class TenantUserRoleRepository(Protocol):
    async def roles_of_user_in_tenant(
        self, tenant_id: TenantId, user_id: UserId
    ) -> list[Role]: ...
    async def assign_role(self, role: TenantUserRole) -> None: ...
    async def remove_role(self, tenant_id: TenantId, user_id: UserId, role_id: RoleId) -> None: ...


class UserGlobalRoleRepository(Protocol):
    async def global_roles_of_user(self, user_id: UserId) -> list[GlobalRole]: ...
    async def assign_global_role(self, role: UserGlobalRole) -> None: ...


class DocumentRepository(Protocol):
    """Registry of tenant-owned documents inside the shared OpenRAG index.

    ``save`` is an aggregate write: it inserts a new row or rewrites every
    mutable field of an existing one. ``created_at`` is set once at insert and
    never rewritten by an update. ``(tenant_id, stored_filename)`` is unique,
    so saving a document that would collide with another row raises at flush;
    callers should look the name up first with ``find_by_stored_filename``.
    """

    async def save(self, document: Document) -> None: ...
    async def find_by_id(self, document_id: DocumentId) -> Document | None: ...
    async def find_by_stored_filename(
        self, tenant_id: TenantId, stored_filename: str
    ) -> Document | None: ...
    async def list_by_tenant(self, tenant_id: TenantId) -> list[Document]: ...
    async def list_stored_filenames(self, tenant_id: TenantId) -> list[str]: ...
    async def delete(self, document_id: DocumentId) -> None: ...
